### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Bottersnike** [HTSTEM/MusicBot#2]
- [x] !help (nicer, custom, one)
- [x] !blacklist
- [x] !bldump
- [x] !clean
- [x] !clear
- [x] !dequeue
- [x] !disconnect
- [x] !forceskip
- [x] !id
- [x] !joinserver
- [x] !listids
- [x] !np
- [x] !pause
- [x] !perms
- [x] !play
- [ ] ~!pldump~ Tant said to not bother with playlists.
- [x] !queue
- [x] !remsong
- [x] !restart
- [x] !resume
- [x] !search
- [x] !setavatar
- [x] !setname
- [x] !setnick
- [ ] ~!shuffle~ Never used
- [x] !shutdown
- [x] !skip
- [x] !summon
- [x] !volume

**Comment by Bottersnike** [comment]
Woot!
